version: '3.9'
services:
  nginx:
    image: nginx:alpine
    ports: ["80:80"]
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on: [php]
  php:
    build: .
    volumes:
      - ./:/var/www/html
    depends_on: [mysql]
  mysql:
    image: mysql:8
    environment:
      MYSQL_DATABASE: translations
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports: ["3306:3306"]
    command: --default-authentication-plugin=mysql_native_password --innodb_ft_min_token_size=2
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
